export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Footer } from './Footer'
export { default as Products } from './Products'
export { default as Steps } from './Steps'
export { default as Testimonial } from './Testimonial'